<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit6c1e8a21e61bab078cc09670537938ba
{
    public static $prefixLengthsPsr4 = array (
        'D' => 
        array (
            'Deljdlx\\FormEditor\\' => 19,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Deljdlx\\FormEditor\\' => 
        array (
            0 => __DIR__ . '/../..' . '/src/class',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit6c1e8a21e61bab078cc09670537938ba::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit6c1e8a21e61bab078cc09670537938ba::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit6c1e8a21e61bab078cc09670537938ba::$classMap;

        }, null, ClassLoader::class);
    }
}
